### ISSUE TITLE
New example

### ISSUE THREAD

**Issue by smithseant** [maljovec/quetzal#9]
Dan,
I have a new example that involves more simulations and sampling of prior & posterior distributions. Also, all my data is encapsulated in one pickle file. It does seem to break the selections. I don't know how you would like me to handle it. I created a separate file (example_sean.py with the pickle file BSF_nonlinear.p) and committed it to my own repo, but don't have permission to push to the remote.
Sean

**Comment by maljovec** [comment]
@smithseant I changed permissions so you should be able to push directly to this repo. I can try to take a look at your new data to see if I can make it work from my end. I was unable to locate your own repo, is it private perchance?

**Comment by smithseant** [comment]
I just pushed.
It would be great if you could correct it. But to be clear, only the brushing/selection wasn't working. It looks really good otherwise.

**Comment by maljovec** [comment]
@smithseant the quick fix is to reorder the way you input the data so that "experiments" does not show up first.

e.g.,
```python
for qoi_type in sim.index.levels[0]:
    dashboard.add_axes(qoi_type)
    dashboard.add_series(qoi_type, "simulations", sim.loc[qoi_type].to_dict())
    dashboard.add_series(qoi_type, "experiments", expt_range(expt, qoi_type))
    dashboard.add_series(qoi_type, "surrogates", surr.loc[qoi_type].to_dict())
    dashboard.add_series(qoi_type, "prior sample", prior_y.loc[qoi_type].to_dict())
    dashboard.add_series(qoi_type, "post. sample", post_y.loc[qoi_type].to_dict())
```

This has to do with the how the plot infers the datatype of each axis by looking at the first series that comes in. Now, it is no longer a number, but an array, and it chokes on that. This is a wholly unsatisfying fix, I realize so I will commit it from my end, but I will leave this ticket open so I know to come up with a more robust solution that does not depend on the operator's in-depth understanding of how the visualization code is working.
